module.exports = {
    ELK_SERVICES_URL: 'https://xgwint.menora.co.il:9450/DigitalBusinessActivityMonitoring/api/v1/logs/bam',
    ELK_API_USERNAME: 'admin ',
    ELK_API_PASSWORD: 'zaq12wsx',
    ELK_LOGGER_LOGSTASH_TAM_URL: process.env.ELK_LOGGER_LOGSTASH_TAM_URL || '172.22.21.4:9602',
    ELK_LOGGER_BAM_URL: process.env.ELK_LOGGER_BAM_URL || 'http://10.172.128.18:8084/api/v1/logs/bam',
    SERVICE_NAME: 'menora.services.bam-ui',
    PORT: process.env.PORT || 3000,
    BASE_API_PATH: '/bamui/api/v1',
    ZIPKIN_PATH: 'http://localhost:9411/api/v1/spans',
    //MONGODB_CONNECTION_STRING: 'mongodb://172.22.5.44:27017',
    MONGODB_CONNECTION_STRING: process.env.MONGODB_CONNECTION_STRING || 'mongodb://digital:digital@mongo4int01,mongo4int02,mongo4int03/userManagement?replicaSet=rsdigital',
    MONGODB_NAME: process.env.MONGODB_NAME || 'digital_bam_ui',
    MONGODB_COLLECTION: process.env.MONGODB_COLLECTION || 'testWithType',
    SECRET_ID: 'I4jB3oJ8qA7hL7gA5pJ5aB8pB3xR5cR6kR5eN4pK6wQ4qC3hD4',
    CLIENT_ID: '9c7296f6-7562-430f-ae4b-deda29c0377b',
    API_USERNAME: "datapower",
    API_PASSWORD: "123",
    PREFIX_PATH: process.env.PREFIX_PATH || "http://localhost",
    VALUES_URL: "http://localhost:3000/bamui/api/v1/values",
    TEST_URL: "http://localhost:3000/bamui/api/v1/test",
    UPDATE_URL: "http://localhost:3000/bamui/api/v1/update",
    // Oauth2 
    TOKEN_URL: process.env.TOKEN_URL || "https://oauth2-mdpint.menora.co.il/api/v1/",
    LOGIN_URL: "http://bam-ui:3000/bamui/api/v1/loginAuthentication",
    // TOKEN_URL: process.env.TOKEN_URL || "http://services-oauth2:3000/api/v1",
    TOKEN_AUTHORIZATION: "Basic YWRtaW46emFxMTJ3c3g=",
    TOKEN_API_BASIC_HTTP_USER_NAME: "admin",
    TOKEN_API_BASIC_HTTP_PASSWORD: "zaq12wsx",
    // ADMIN_TOKEN_USERNAME: "BAMUI_API",
    // ADMIN_TOKEN_PASSWORD:"bamui12api",
    ADMIN_TOKEN_ROLE:"BAMUI",
    API_USER_NAME_FOR_TOKEN: "BAMUI_API",
    API_PASSWORD_FOR_TOKEN: "bamui12api",
}